### ISSUE TITLE
Keys for testing for non-p2p-org members?

### ISSUE THREAD

**Issue by rabble** [p2p-org/p2p-wallet-ios#35]
Hi,

Where does a third party developer go about getting / generating keys for testing / developing the app?

RPCPOOL_API_KEY = <your_key>

TRANSAK_STAGING_API_KEY = <your_key>
TRANSAK_PRODUCTION_API_KEY = <your_key>
TRANSAK_HOST_URL = <your_key>

// Mark: - Moonpay
MOONPAY_STAGING_API_KEY = <your_key>
MOONPAY_PRODUCTION_API_KEY = <your_key>

// MARK: - CryptoCompareAPI
CRYPTO_COMPARE_API_KEY = <your_key>

// MARK: - Amplitude
AMPLITUDE_API_KEY = <your_key>

// MARK: - FeeRelayer
FEE_RELAYER_ENDPOINT = <your_key>

**Comment by bigearsenal** [comment]
Hi there, here you are

// MARK: - Transak
TRANSAK_STAGING_API_KEY = fake_api_key
TRANSAK_PRODUCTION_API_KEY = fake_api_key
TRANSAK_HOST_URL = p2p.org

// Mark: - Moonpay
MOONPAY_STAGING_API_KEY = fake_api_key
MOONPAY_PRODUCTION_API_KEY = fake_api_key

// MARK: - Amplitude
AMPLITUDE_API_KEY = fake_api_key

// MARK: - FeeRelayer
FEE_RELAYER_ENDPOINT = fee-relayer.solana.p2p.org
