### ISSUE TITLE
KeyAppUI access

### ISSUE THREAD

**Issue by maceip** [p2p-org/p2p-wallet-ios#749]
compilation is blocked without access to KeyAppUI. github.com:p2p-org/KeyAppUI.git is private.

Can you either provide a xcframework library for KeyAppUI or provide access to the git repo directly?

cc @lisemyon

**Comment by bigearsenal** [comment]
@maceip hi there. I'm asking my superior about opening source code of KeyAppUI, will get back to you soon

**Comment by TrGiLong** [comment]
KeyAppUI is public right now
